# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ssIsmeg7ua2Dd8Bps4xQOBXnjZMOWSQ6
"""

!pip install flask tensorflow numpy pillow

!pip install uvicorn

!pip install fastapi

!pip install tensorflow

!pip install flask flask-ngrok

import os
print(os.path.exists("/content/mnist_model.h5"))  # Should print True

from flask import Flask, request, jsonify
from flask_ngrok import run_with_ngrok
import tensorflow as tf
import numpy as np
from PIL import Image
import io

app = Flask(__name__)
run_with_ngrok(app)

# Load the model
model = tf.keras.models.load_model("/content/mnist_model.h5")

@app.route("/predict", methods=["POST"])
def predict():
    if "file" not in request.files:
        return jsonify({"error": "No file uploaded"}), 400

    file = request.files["file"]
    img = Image.open(io.BytesIO(file.read()))
    img = img.resize((28, 28)).convert("L")  # Convert to grayscale
    img_array = np.array(img) / 255.0
    img_array = img_array.reshape(1, 28, 28, 1)

    predictions = model.predict(img_array)
    probabilities = {i+1: float(prob) for i, prob in enumerate(predictions[0])}

    return jsonify({"probabilities": probabilities})

if __name__ == "__main__":
    app.run()

import os
print(os.listdir())  # Check if "mnist_model.h5" is listed

from google.colab import files
files.upload()  # Select "mnist_model.h5" from your system

import shutil
shutil.move("Mnist.ipynb", "/content/mnist_model.h5")

